### ISSUE TITLE
Provide an example of db.cfg file structure

### ISSUE THREAD

**Issue by dzei** [franz-see/Robotframework-Database-Library#101]
I'd like to use Connect To Database keyword using db.cfg file. However documentation doesn't provide example of what kind of file structure should be used in the file.

**Comment by browncrane** [comment]
With several tries, get `NoSectionError: No section: 'default'` at dead end.  
Not sure what's the real problem.

**Comment by browncrane** [comment]
The following format is working for me.
```
[default]
dbapiModuleName=pymysqlforexample
dbName=yourdbname
dbUsername=yourusername
dbPassword=yourpassword
dbHost=yourhost
dbPort=yourport
```

**Comment by jerry57** [comment]
This is now in the master branch and will be released in next version.
