### ISSUE TITLE
Return number of rows affected by execute

### ISSUE THREAD

**Issue by kivipe** [franz-see/Robotframework-Database-Library#104]
I would like to get number of rows affected by Execute SQL Script and Execute SQL String keywords. PyMySQL already returns number of rows when cursor is executed but this is not passed back to Robot Framework.

This functionality is opposite to what is requested in #74. However, I feel that Execute keywords should not be used to run SQL queries.

**Comment by kivipe** [comment]
I like how you have separated sql queries and executes. Making one thing to do two things is usually a source of complexity so I like to keep them separate. Also it might change existing functionality. Here is my proposal, I will try to code it if you agree. This should be two pull requests:

1. make `execute_sql_script` and `execute_sql_string` return row count
2. create keyword `query_script` to mimick `execute_sql_script`and handle #74

**Comment by jerry57** [comment]
This sounds like an excellent way to go.  Any chance you could submit pull requests reflecting the above along with possible testcases?  We could also update the documentation for these keywords, clarifying their intended usages and returns.

**Comment by jerry57** [comment]
Closing, as this is now merged into master
