### ISSUE TITLE
Execute Sql Script fails when using psycopg2

### ISSUE THREAD

**Issue by OMG-WhatDoYouMeanMyUsernameIsTaken** [franz-see/Robotframework-Database-Library#107]
The `Execute Sql Script` keyword attempts to [add the return code of the execution to any previous return codes](https://github.com/franz-see/Robotframework-Database-Library/blob/35b86ca0888f4b38eb61ad64afbd904ead16349f/src/DatabaseLibrary/query.py#L282) (or zero if there haven't been). The problem is that [psycopg2 returns None from cursor.execute](http://initd.org/psycopg/docs/cursor.html#cursor.execute) which causes an exception to be thrown.

`TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'`

**Comment by jerry57** [comment]
Is this happening after the latest release (v1.2) or before (v1.1.1)?

**Comment by OMG-WhatDoYouMeanMyUsernameIsTaken** [comment]
It's happening in 1.2

**Comment by jerry57** [comment]
Unfortunately this is a known issue with the latest deployment and changes. I have reverted the code for now, and will do a new release soon. Please use v1.1.1 until then. Sorry for the inconvenience.

**Comment by meuchel** [comment]
is there a workaround?

**Comment by jerry57** [comment]
changes to Execute SQL have been reverted and pushed to v1.2.1 and current master
