### ISSUE TITLE
TypeError when using keyword "Execute Sql Script" for deleting rows from DB2

### ISSUE THREAD

**Issue by Veronit** [franz-see/Robotframework-Database-Library#110]
After 1.2 update we get error "TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'" when using keyword "Execute Sql Script" for deleting rows from DB2 database. Robot debug log show that the error comes from src/DatabaseLibrary/query.py and from row 282.

Script file contains multiple rows like this:
delete from table1;
delete from table2;

In 1.1.1 deleting works fine.

The issue I believe comes from this change: https://github.com/franz-see/Robotframework-Database-Library/commit/0988750502c08d7825b87c2daa0176422f56bd6c#diff-39e550436c9a9a02988db063e0dc0d8b

**Comment by jerry57** [comment]
Unfortunately this is a known issue with the latest deployment and changes.  I have reverted the code for now, and will do a new release soon.  Please use v1.1.1 until then.  Sorry for the inconvenience.

**Comment by Veronit** [comment]
No problem! We already downgraded to 1.1.1, so no rush.
I just noticed that there is already a bug about the same issue. I'll close this one as duplicate.
