### ISSUE TITLE
Return Query Result Extra Characters 

### ISSUE THREAD

**Issue by casidos** [franz-see/Robotframework-Database-Library#112]
Hello,

When the query return the result I got this extra characters.

Example:

('Query Result',) Expected Query Result

Thanks

**Comment by jerry57** [comment]
Docs shows that results are returned as an array/list:

${queryResults}	Query	SELECT first_name, last_name FROM person
Log	${queryResults[0][1]}, ${queryResults[0][0]}

**Comment by casidos** [comment]
That's right .. 

The return of the Query is a tuple.

Is more easy if the user use the second argument that return a Dictionary.
