### ISSUE TITLE
robotframework-databaselibrary 1.2 SQL execution script error

### ISSUE THREAD

**Issue by sabyasachisabs** [franz-see/Robotframework-Database-Library#113]
Installed version: Python2.7

The following test case results in the below error:

Testcase DB Truncate
`   Full Cleardown `
`    [Arguments]    ${tc_number} `
`    Connect As db_name `
`    ${output} =    Execute Sql Script  ${CURDIR}/Test Case 001/truncate.sql `
`    Disconnect From Database`

Content of "truncate.sql"

`
  truncate table sw_core.actual_flow_in;
`
Results in below error:
`
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
`
**This error doesnt occur with robotframework-databaselibrary with 1.1.1** but with 1.2

Installed version:
<code>
Collecting robotframework
  Downloading https://files.pythonhosted.org/packages/36/c6/6f89c80ac5a526a091bd383ffdfc64c9a68d9df0c775d4b36f03d8e0ac25/robotframework-3.1.1-py2.py3-none-any.whl (601kB)
Collecting robotframework-databaselibrary
  Downloading https://files.pythonhosted.org/packages/46/75/969176c4499f435ebd1545e2d8c5cac797005e6309860dbd95316eda5cb5/robotframework-databaselibrary-1.2.tar.gz
Collecting robotframework-sshlibrary
  Downloading https://files.pythonhosted.org/packages/73/10/cf734db65f90a39b2c37d011083d2448dbd36fd560bf4201421eda9d5e39/robotframework-sshlibrary-3.3.0.tar.gz (45kB)
Collecting robotframework-csvlibrary
  Downloading https://files.pythonhosted.org/packages/03/b5/f5bf0d52a42c498384d5fad88c8d57fc33f060b46bb608cb750bc0927d41/robotframework-csvlibrary-0.0.2.tar.gz (54kB)
Collecting robotframework-dependencylibrary
  Downloading https://files.pythonhosted.org/packages/56/7d/2491fca1127f6a042a2ba8da91f349f0d42cfc911ff9aab24c6b1c73593d/robotframework-dependencylibrary-1.0.0.post1.tar.gz
Collecting cx_Oracle
  Downloading https://files.pythonhosted.org/packages/6e/88/d8bf4d511231f2e96866d068ebf71278c611296acb803520658d3735e980/cx_Oracle-7.1.1-cp27-cp27mu-manylinux1_x86_64.whl (674kB)
</code>

**Comment by jerry57** [comment]
Unfortunately this is a known issue with the latest release.  I have rolled the changes back in master, but have not had a chance to do a new release yet.  Please use v1.1.1 or install from source, master branch.  Thx

**Comment by sabyasachisabs** [comment]
Thanks for the confirmation.
And all the best to address the issue.

**Comment by eric-benoit** [comment]
@jerry57 I just downloaded the master branch and the bug is still there... are you sure it has been rolled back in master? If not, when do you plan to do it? Thanks!

**Comment by jerry57** [comment]
Changes for Execute SQL have been reverted and now on Master along with new release v1.2.1

**Comment by eric-benoit** [comment]
@jerry57 Thanks for the feedback.
Unfortunately I am not able to install the version 1.2.1 for Python 2.7...
I am getting this error:
`Collecting robotframework-databaselibrary==1.2.1
[91m  ERROR: Could not find a version that satisfies the requirement robotframework-databaselibrary==1.2.1 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.8, 0.8.1, 1.0.0, 1.0.1, 1.1, 1.1.1, 1.2)
[0m[91mERROR: No matching distribution found for robotframework-databaselibrary==1.2.1
[0mThe command '/bin/sh -c pip install robotframework-databaselibrary==1.2.1' returned a non-zero code: 1`

After checking this site: https://pypi.org/simple/robotframework-databaselibrary/ I can see that only the Python 3 version of the library is available.

Is it possible to make the Python 2.7 version available as well?

Thanks!

**Comment by jerry57** [comment]
Can you install via:
pip install git+https://github.com/franz-see/Robotframework-Database-Library

I will see about getting a 2.7 build, but not setup at the moment.  Above should install from source.
