### ISSUE TITLE
establish sybase connection

### ISSUE THREAD

**Issue by pwalaszkowski** [franz-see/Robotframework-Database-Library#114]
Hi, 

This is not an issue at all. I'm just looking an answer, is it possible to connect to Sybase database?
I prepared some solutions in Python, but my code will be used with QA guys who doesn't know Python very well and it's better to use Database Library

Thanks!

**Comment by jerry57** [comment]
Yes it should as long as there is a DB API 2.0 module.  I have not tested it myself though, don't have Sybase installed anywhere.  What module are you using for your python code?

**Comment by pwalaszkowski** [comment]
I normally use SQL Alchemy. 

I've try to use your DatabaseLibrary and for Sybase i've got following error:
`OperationalError: ('08001', '[08001] [Microsoft][ODBC SQL Server Driver][DBNETLIB]SQL Server does not exist or access denied. (17) (SQLDriverConnect); [08001] [Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionOpen (Connect()). (53)')`

I've also try to use Postgres and that works great!

**Comment by jerry57** [comment]
I have not tried SQLAlchemy but there is a fork of this library that uses it:
https://github.com/edbrannin/Robotframework-SQLAlchemy-Library
When you get the error, can you show me the code you are using for connect?
Also, can you send me your SQL Alchemy connection string?  I might be able to figure out how to get it working with DatabaseLibrary

**Comment by pwalaszkowski** [comment]
Hi, i've get it
I've used the custom params keyword 
  
`connect to database using custom params  pyodbc  "Driver={${Sybase_DBDriver}}; server=${Sybase_DBHost}; port=${Sybase_DBPort};db=${Sybase_DBName}; uid=${Sybase_DBUser}; pwd=${Sybase_DBPass};"`

I think that we can close this issue

**Comment by jerry57** [comment]
Glad to hear you got it working.  I will see if I can improve the docs a little more to help out in the future as a separate issue
