### ISSUE TITLE
Need to be able to set pyodbc.pooling to False

### ISSUE THREAD

**Issue by pepik-knize** [franz-see/Robotframework-Database-Library#118]
Hello,

I'm trying to connect to Teradata from a Linux server, and kept running into this error: "Unable to set SQL_ATTR_CONNECTION_POOLING attribute." After finding [this page from Teradata](https://downloads.teradata.com/blog/odbcteam/2016/02/python-with-teradata-odbc) that had me install pyodbc with some tweaks, it also says that before attempting the connection that we must set pyodbc.pooling to False. I didn't see any way to do that other than hacking connection_manager.py and setting it there. This is working for me for now, but I'd obviously like a supported way to do it. 

This is how I hacked it, I'm sure there's a better way:
```
    # added the connection_pooling parameter here, plus one more line down below:
    def connect_to_database_using_custom_params(self, dbapiModuleName=None, db_connect_string='', connection_pooling=True):
        """
        Loads the DB API 2.0 module given `dbapiModuleName` then uses it to
        connect to the database using the map string `db_custom_param_string`.

        Example usage:
        | # for psycopg2 |
        | Connect To Database Using Custom Params | psycopg2 | database='my_db_test', user='postgres', password='s3cr3t', host='tiger.foobar.com', port=5432 |

        | # for JayDeBeApi |
        | Connect To Database Using Custom Params | JayDeBeApi | 'oracle.jdbc.driver.OracleDriver', 'my_db_test', 'system', 's3cr3t' |
        """
        db_api_2 = importlib.import_module(dbapiModuleName)
        # added this next line:
        db_api_2.pooling = connection_pooling
        db_connect_string = 'db_api_2.connect(%s)' % db_connect_string

        self.db_api_module_name = dbapiModuleName
        logger.info('Executing : Connect To Database Using Custom Params : %s.connect(%s) ' % (dbapiModuleName, db_connect_string))
        self._dbconnection = eval(db_connect_string)

```

Thank you!

**Comment by jerry57** [comment]
Glad you were able to come up with a workaround, but that doesn't look like a good permanent solution.  If you can submit a pull request for a better solution, that would be greatly appreciated.
