### ISSUE TITLE
Cannot connect to MySQL8 database via SSH

### ISSUE THREAD

**Issue by jezebeth** [franz-see/Robotframework-Database-Library#119]
I use ssh to connect to remote mysql server and bound to localhost, port 3350.

I found an error OperationalError: (1045, u"Access denied for user 'dbUser'@**'10.21.18.40'** (**using password: NO**)") while connecting database using command:

_Connect to database    pymysql    dbName=myDbName    dbUsername=myDbUser    dbPassword=myDbPassword    dbPort=3350    **dbHost=127.0.0.1**_

I'm not really sure why the error using IP address of ssh server instead of localhost with using password = NO.
I try to connect using mysql command and it can connect to database properly.
Here is my command which is exactly use the same parameters as when I called via Database Library:
mysql -u myDbUser -pmyDbPassword  -D myDbName -h 127.0.0.1 -P 3350

**Comment by jerry57** [comment]
Using the IP should not affect the connection.  I do have to ask, are you sure you are using the correct port, above you reference 3350 in the Connect to Database keyword,  but use 3335 in the direct mysql connection string?

**Comment by jezebeth** [comment]
> Using the IP should not affect the connection. I do have to ask, are you sure you are using the correct port, above you reference 3350 in the Connect to Database keyword, but use 3335 in the direct mysql connection string?

Sorry for my typo, I updated my issue already. I use mysql command and also try with Sequel Pro to connect to port 3350 and it can connect successfully.
