### ISSUE TITLE
Error in Driver={Sql Server}

### ISSUE THREAD

**Issue by alejan2x** [franz-see/Robotframework-Database-Library#120]
You have a big fail in you connection in the file connection_manager.py

I ran in docker and linux and ever show me the same error,  I use pyodbc with differents versions 17, 13, 13.01. 

https://docs.microsoft.com/en-us/sql/connect/python/pyodbc/step-1-configure-development-environment-for-pyodbc-python-development?view=sql-server-2017

pyodbc.Error: ('01000', "[01000]" [unixODBC][Driver Manager]Cant open lib 'SQL Server':file not found(0) (SQLDriverConnect)").

![fail](https://user-images.githubusercontent.com/28353371/64130705-b73db900-cd89-11e9-9929-478b71ebb844.png)

I reviewed you file and you are using to connect SQL : **Driver={SQL Server }**

![file](https://user-images.githubusercontent.com/28353371/64130745-ea804800-cd89-11e9-9ea5-384870098eb3.jpg)

take the decision of change the varible **Driver={ODBC Driver 17 for SQL Server}**, and vualaaaa, now run correctly. 

![ok](https://user-images.githubusercontent.com/28353371/64130710-c02e8a80-cd89-11e9-901e-52d9e0c88cff.png)

**Comment by jerry57** [comment]
I am not sure what the errors are you are seeing, but using "Driver={SQL Server}" allows for versioning to be handled outside of the driver.  I have this currently running on Windows, Mac OX X and Linux.

**Comment by alejan2x** [comment]
I did do exactly that you mentioned, edit the file of /etc/odbcinst.ini and just now run correctly. 

tnks

**Comment by jerry57** [comment]
No problem and glad to hear it is working for you!  Enjoy...
