### ISSUE TITLE
Support for SAP HANA

### ISSUE THREAD

**Issue by Bowbear** [franz-see/Robotframework-Database-Library#121]
I think it would be a good idea having support for SAP HANA DB as well and would appreciate if this could be realized.

**Comment by jerry57** [comment]
Have you tried using it at all?  Are you getting errors with "Connect to Database" or "Connect to Database Using Custom Params" keywords?  If errors, what are they?

**Comment by jerry57** [comment]
In reading through the basic SAP HANA documentation, it appears to be dbapi 2.0 compliant and should work.  If you are getting errors, please file an issue with those details.
