### ISSUE TITLE
Documentation of the keyword 'Connect To Database Using Custom Params'

### ISSUE THREAD

**Issue by ericxbenoit** [franz-see/Robotframework-Database-Library#125]
In the keyword documentation of the keyword 'Connect To Database Using Custom Params', there is an example of usage with JayDeBeApi. The first argument of the keyword is 'JayDeBeApi' written in camel case. However the keyword does not work properly if the value is not all lower case.

Would it be possible to change the documentation to reflect that it must be lower case like that: jaydebeapi ?

> """
        Loads the DB API 2.0 module given `dbapiModuleName` then uses it to
        connect to the database using the map string `db_custom_param_string`.
        Example usage:
        | # for psycopg2 |
        | Connect To Database Using Custom Params | psycopg2 | database='my_db_test', user='postgres', password='s3cr3t', host='tiger.foobar.com', port=5432 |
        | # for JayDeBeApi |
        | Connect To Database Using Custom Params | **_JayDeBeApi_** | 'oracle.jdbc.driver.OracleDriver', 'my_db_test', 'system', 's3cr3t' |
        """

Thanks

**Comment by jerry57** [comment]
Corrected on master now, will go with next release.
