### ISSUE TITLE
Encoding issue with chinese characters using Execute Sql Script

### ISSUE THREAD

**Issue by HHDDLL** [franz-see/Robotframework-Database-Library#126]
When I try to execute a sql file with some chinese word , it got encoding error 
The problem is solved for me when I change line 251 in query.py from function【execute_sql_script】:

sqlScriptFile = open(sqlScriptFileName)

To

sqlScriptFile = open(sqlScriptFileName,encoding='UTF-8')

Then everythiong went well

**Comment by jerry57** [comment]
Thanks for reporting this problem.  Can you please submit a pull request with this change and maybe add a testcase about it as well?  I will try to look into the problem more.

**Comment by HHDDLL** [comment]
> Thanks for reporting this problem. Can you please submit a pull request with this change and maybe add a testcase about it as well? I will try to look into the problem more.

ENV info
 os : windows10  chinese
 db: mysql 5.7

code in test.sql:
`select * from t_auth_user where user_name='中国';`

Testcase:
`*** Settings ***
Library           DatabaseLibrary    
*** Test Cases ***
Test Encoding
    #Connect To Database Using Custom Params    pymysql    database='database',user='user',password='password',host='127.0.0.1',port=3306
    Execute Sql Script    ${CURDIR}/test.sql`

I have submited a pull request

**Comment by jerry57** [comment]
Please add testcases to the PR.
