### ISSUE TITLE
skip control characters at beginning of PGAdmin3 script

### ISSUE THREAD

**Issue by ccurvey** [franz-see/Robotframework-Database-Library#13]
definitely a feature -- when I create a SQL Script in PGAdmin3 on Windows, it puts three extra control characters at the beginning of the file.  "od" tells me that they are 357 273 277.  When I run the script through the robot framework, I get a syntax error near "insert".  

The workaround is to create my scripts in vim for Windows, but it would sure be nice if I could refine my scripts in a database tool.

P.S.  vim seems to recognize these characters for whatever they are, and does not display them.

**Comment by jerry57** [comment]
Any chance you could submit a pull request with the changes required?  I will get it reviewed and merged as quickly as possible.
