### ISSUE TITLE
Long query

### ISSUE THREAD

**Issue by akyaseen** [franz-see/Robotframework-Database-Library#139]
I want to run long queries to the function which can go to multiple lines. For example

    Row Count Is 0    SELECT * FROM person
... WHERE last_name = 'Baggins'

Verify Query - Row Count person table 0 row                           | FAIL |
Expected zero rows to be returned from 'SELECT * FROM person' but got rows back. Number of rows returned was 2
------------------------------------------------------------------------------
... WHERE last_name = 'Baggins'                                       | FAIL |
Test case contains no keywords.

Its not considering the next line as part of the query and runs as a different test case. This is just example, I have queries which are long and need to be different lines to maintain clarity in reading them.

**Comment by jerry57** [comment]
Without seeing your code I am assuming this will solve your problem.

    ${sqlstmt} =     Catenate    SELECT *
    ...      FROM person
    ...      WHERE lastname = 'Baggins'
    Row Count Is 0    ${sqlstmt}

**Comment by akyaseen** [comment]
yeah... Thanks Jerry.
