### ISSUE TITLE
Encrypted password to connect to database

### ISSUE THREAD

**Issue by akyaseen** [franz-see/Robotframework-Database-Library#140]
Hi,

Currently I don't see a way to pass encrypted password to connect to database. Is there way to do it? If not, is it possible to add this feature.

**Comment by jerry57** [comment]
Hi,
I am not aware of a way to pass encrypted passwords to any databases for connection.  Could you please explain exactly what you are trying to achieve?  Maybe with a python example?

**Comment by akyaseen** [comment]
Basically i create a resource file to store the Database connection parameters as below:

*** Variables ***
${DBHost}         127.0.0.1
${DBName}         MYDB
${DBPass}         mypasswd
${DBPort}         52892
${DBUser}         myuser
${dbDriver}       ODBC Driver 17 for SQL Server

As I want to hide or encrypt it, so its not visible to everyone who has access to the resource. I explored a bit and found a CryptoLibrary which can hide the passwords. Also I found as I said we cannot pass encrypted password to any databases for connection.  Please let me know if you know any other mechanism other than the CryptoLibrary and close the issue. Thanks for the reply.

**Comment by jerry57** [comment]
Short of writing your own encrypt/decrypt as a keyword in Robotframework and passing it your resource file before a run, I do not know of a way.  You could create and Arguments file and store that in something like KeePass where it would be separate from your code.  Check that out and pass on the robot command like like "robot -A MyArgumentsVars.arg ......"  This is what we do where I am now to restrict access to sensitive info.  In our RF code we don't define variables with real info, but rather pass it in as an override arguments file.

Sample file
MyArgumentsVars.arg
------------------------
--variable DBHost:127.0.0.1
--variable DBName:MYDB
--variable DBPass:mypasswd
--variable DBPort:52892
--variable DBUser:myuser
--variable dbDriver:ODBC Driver 17 for SQL Server

You can also comment out lines by putting a "#" at the beginning of the line like:
#--variable DBPort:52892

Then it would use whatever is defined in your resource file.

Hope this helps out.
