### ISSUE TITLE
Site Link is not working

### ISSUE THREAD

**Issue by damies13** [franz-see/Robotframework-Database-Library#144]
FYI The main site is not working anymore:
http://franz-see.github.com/Robotframework-Database-Library/

I found out from this forum post:
https://forum.robotframework.org/t/invalid-website-link-for-database-library-python/1677

**Comment by jerry57** [comment]
Thanks for the heads up.  It appears github.com is no more and now is github.io.  I will get the links updated as quickly as possible.
https://franz-see.github.io/Robotframework-Database-Library/ is up and running though.
