### ISSUE TITLE
How can we validate IndexedDB data using Robot Framework

### ISSUE THREAD

**Issue by MrunaliBokde** [franz-see/Robotframework-Database-Library#165]
I am trying to get data from IndexedDB and validate with the expected value using below code in Robot Framework.

*** Settings ***
Library           SeleniumLibrary

*** Test Cases ***
TestIndexedDB
    Open Browser    ${URL}    ${BROWSER}
    Go To    ${URL}
    ${db_conn}=    Execute JavaScript    window.indexedDB.open('Database', 1)
    ${transaction}=    Execute JavaScript    ${db_conn}.transaction('Object_store', 'readonly')
    ${object_store}=    Execute JavaScript    ${transaction}.objectStore('Object_store')
    ${cursor}=    Execute JavaScript    ${object_store}.openCursor()
    ${content}=    Execute JavaScript    ${cursor}.value
    Run Keyword If    '${content.key}' == 'value'    Log    Content verification successful

But I am getting "None" value as return in ${db_conn} and my next step is failing.

Hi @HelioGuilherme66, could you please help me to solve this issue and to get required value from indexedDB.

**Comment by HelioGuilherme66** [comment]
@MrunaliBokde Your test is not using this DatabaseLibrary. This issue is a question, and you should not use an Issue Tracker for requests of support. Please ask in a proper site or service. You have from https://robotframework.org a section of where you can ask for support.

**Comment by MrunaliBokde** [comment]
Hi @HelioGuilherme66 , I am new to github, thank you for guiding me. I will raise my question in mentioned site.
