### ISSUE TITLE
Row Count Keyword always returns -1

### ISSUE THREAD

**Issue by vipulchawla** [franz-see/Robotframework-Database-Library#22]
I have the Database Library in Place.
I am using the following Keyword
${RowCount} Row Count   SELECT \*  FROM DIRGRP.ALIANC

It is always returning -1 irrespective of the query used

I am using Seleniumversion 2.24
Not sure if this was fixed in a later version. If yes, then please let me know the version number.

**Comment by sdhall** [comment]
Version 0.7 is still not available via pip. Is there a plan to make it available via pip?
