### ISSUE TITLE
Connect To Database ibm-db Windows path problem

### ISSUE THREAD

**Issue by Houbein** [franz-see/Robotframework-Database-Library#227]
Previously I've had to implement the ibm-db fix for windows. This is now built-in to this library. But there is still a problem. 
Soms tests give the error: FileNotFoundError: [WinError 206] The filename or extention is too long: 'C:\\Python311\\Lib\\site-package\\clidriver\\bin' 
Only some tests in our suit give this error, not all. If I run a test that gives this error in a full suite run individually, it does not give this error. 
I've tried implementing the registry value to allow Windows to ignore the standard limited file path length, without succes. 
I've tried making the path between the test suite and the clidriver much shorter, to within even the normal Windows standard, without succes. 
I am out of ideas, can anyone here help?

**Comment by amochin** [comment]
Could you provide a RF test execution log?
In particular I’m interested, if establishing the connection happens a lot of times during the test execution? Just thinking - maybe the total length of windows path where to look for variables gets too long…

**Comment by amochin** [comment]
For debugging, I’d try to print the out the current list of DLL paths each time when the CLI driver path is added - [here](https://github.com/MarketSquare/Robotframework-Database-Library/blob/1182dd09de3b8fa1727328f94909d7af69c85acf/src/DatabaseLibrary/connection_manager.py#L331). Do you think you could try it?

**Comment by amochin** [comment]
I've just release version 2.0.4 with a fix, which adds a driver path only once even if there are multiple connections in the test execution - could you please try if it solves the issue?
