### ISSUE TITLE
JayDeBeApi 0.1.4 breaks 'Connect To Database Using Custom Params'

### ISSUE THREAD

**Issue by mauricekoster** [franz-see/Robotframework-Database-Library#25]
New JayDeBeApi now honors CLASSPATH, but in doing so it modified the connect() method breaking 'Connect To Database Using Custom Params'

**Comment by jerry57** [comment]
Please feel free to submit a pull request with corrective actions.  Also need more info on what broke if possible.

**Comment by jerry57** [comment]
Closing as I believe this is no longer an issue
