### ISSUE TITLE
Sql script file handled incorretly if statements contain semicolon(;) character in unexpected place

### ISSUE THREAD

**Issue by fedulovivan** [franz-see/Robotframework-Database-Library#31]
Noticed that file contents with list of multiple sql queries is handled incorretly, and this causes sql exption like _ORA-01756: quoted string not properly terminated_ (in case of working with oracle) if statements contain semicolon(;) character in unexpected place.

Steps to reproduce:
- create sql script file quiery.sql containing something like:
  _INSERT INTO FILES('ID', 'NAME') VALUES ('1', 'Any; name');_
- execute command Execute Sql Script  quiery.sql

So semilcolon after word "Any" confuses function _execute_sql_script_ (line 205 of query.py)

**Comment by rmerkushin** [comment]
Patch (221 line of query.py): sqlFragments = line.split(';') - replace with - sqlFragments = line.split(';\n')

**Comment by bsnow1220** [comment]
when I modified query.py and run,i got the following error:
FAIL - ProgrammingError: (2014, "Commands out of sync; you can't run this command now")
 DEBUG - Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/DatabaseLibrary/query.py", line 236, in execute_sql_script
    self._dbconnection.rollback()

**Comment by lucaspottersky** [comment]
I don't have the skills to write Python code, but I think someone could try to replace `sqlFragments = line.split(';')` with something like `sqlFragments = regex.split(''[^']*'|(;)')`.

This regex tries to match the semicolon, except when it is surrounded by quotes.

http://stackoverflow.com/questions/23589174/regex-pattern-to-match-excluding-when-except-between?lq=1
