### ISSUE TITLE
It does not support ibm_db

### ISSUE THREAD

**Issue by ghost** [franz-see/Robotframework-Database-Library#35]
I tried  to use ibm_db module to connect DB2, but an error occured.

> > > db_api_2 = __import__('ibm_db')
> > > db_api_2.connect (database='SDMRU',user='xxxx', password='xxxx')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > TypeError: function takes at least 3 arguments (0 given)

**Comment by jastako** [comment]
Hi Steven,

Did you manage to solve the problem? I'm experiencing the same right now.

Thanks,
Jakub

**Comment by jerry57** [comment]
Can you send what your problem is, this old github issue was resolve mar 
of last year?  Please include a sample that shows the error and logs?

thx,
jer


On 12/7/15 12:49 AM, jastako wrote:
>
> Hi Steven,
>
> Did you manage to solve the problem? I'm experiencing the same right now.
>
> Thanks,
> Jakub
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/franz-see/Robotframework-Database-Library/issues/35#issuecomment-162439801>.
>

-- 
Linux registered user #475536
Ubuntu registered user #28583

**Comment by jastako** [comment]
Hi Jerry,

Thanks for reply, however I already decided to provide my own implementation of DatabaseLibrary, based on SQLAlchemy and it works like a charm.

Thanks,
Jakub

**Comment by jerry57** [comment]
If possible, I would be interested in seeing your implementation.  Can you send a link?

**Comment by jastako** [comment]
I'd love to, but it's a part of proprietary software.

However it's not difficult. So far there're only 4 keywords implemented:
- db connect,
- db disconnect,
- stored procedure call,
- sql query.

SQLAlchemy comes really helpful, so you can imagine all of the keywords are single, or just few lines long.
