### ISSUE TITLE
Pass parameters to cur.execute()

### ISSUE THREAD

**Issue by edbrannin** [franz-see/Robotframework-Database-Library#40]
It would be nice if Query.query() could accept positional and/or keyword arguments[1] and pass them to [the DB API's execute() method](https://www.python.org/dev/peps/pep-0249/#id15).

This way, we could write queries like this (depending on the DB Driver):

| Keyword | sql | params |
| --- | --- | --- |
| Query | select \* from people where id = ? | ${1} |
| Query | select \* from people where id = :id | id=${1} |

[1]: The keyword could complain if it gets both sequence & mapped parameters at once, or the wrong kind for the current DB Driver's [paramstyle](https://www.python.org/dev/peps/pep-0249/#paramstyle)

**Comment by jerry57** [comment]
Please feel free to submit a pull request, I will review and merge it as quickly as possible.

**Comment by jerry57** [comment]
closing, parameters are accepted as part of the sql string.
