### ISSUE TITLE
Delegate to sqlalchemy?

### ISSUE THREAD

**Issue by edbrannin** [franz-see/Robotframework-Database-Library#43]
I've been considering making a Robot Framework SQLAlchemy library, and it seems good to ask first if there are any plans to delegate to sqlalchemy [as suggested here](https://www.openhub.net/p/robotframework-databaselibrary) (in which case I'd work on a pull request instead of a new project), or if you'd rather keep this library using straight DBAPI.

**Comment by jerry57** [comment]
I am in a bit of a quandary here.  This project was based on DB API 2.0 and may not be the best place to introduce SQLAlchemy.  That being said, personally I would love to see the differences SQLAlchemy might have for this project.  Coding it up and doing a pull request would be nice.  Worst case, it would be rejected and could be taken to a different project.  Either way I would love to see the differences, so please keep me informed on your decision.

I am not sure who submitted the article you referenced, sorry, I couldn't find many details for it.

**Comment by jerry57** [comment]
This project is staying DBAPI 2.0 compliant.  Thanks for submitting all this and creating the new project.  For those interested, please checkout:
https://github.com/edbrannin/Robotframework-SQLAlchemy-Library
