### ISSUE TITLE
dbHost in dbConfigFile is allways 'localhost'

### ISSUE THREAD

**Issue by Stefan1972** [franz-see/Robotframework-Database-Library#47]
when storing the db-configuration in dbConfigFile, the variables dbHost and dbPort are allways 'localhost' and '5432', because of line 68 and 69 in connection_manager.py .

**Comment by jerry57** [comment]
Please submit a pull request for this change and I will get it merged and pushed.  Thanks

**Comment by jerry57** [comment]
Please retest this now, the latest code no longer forces them.

**Comment by jerry57** [comment]
Closing issue as I believe it is now resolved
