### ISSUE TITLE
RowCount doesn't work with pyodbc using SQL Server Native Client driver

### ISSUE THREAD

**Issue by mrooschuz** [franz-see/Robotframework-Database-Library#55]
We use [pyODBC](http://mkleehammer.github.io/pyodbc/) for connection to a MSSQL DB. Full robot line would be: `Connect To Database Using Custom Params    pyodbc    "DRIVER={SQL Server Native Client 10.0}; SERVER=${DATABASE_SERVER}; DATABASE=${DATABASE_NAME}; Trusted_Connection=yes;"` This returns a -1 with the `rowCount = cur.rowcount` in the Query class. If I add pyodbc to the list of module APIs(`if self.db_api_module_name in ["sqlite3", "ibm_db", "ibm_db_dbi"]:`), then it returns the correct row count.

Could you maybe add pyodbc to the list that hits the `rowCount = len(data)`? I can't say with any certainty if this will/won't cause issues with other drivers using pyodbc though. Thought I could at least open a discussion on that.

**Comment by jerry57** [comment]
I believe this is now resolved with the code in master.  Please install from there (not pypi) and retest.  If it is not, please let me know as soon as possible.  Also feel free to submit a pull request and I will review and merge as quickly as possible

**Comment by jerry57** [comment]
Closing as nothing further heard on this and I believe issue is resolved.
