### ISSUE TITLE
execute_sql_script fails to complete if there are lines starting with -- (lines commented out)

### ISSUE THREAD

**Issue by nigotiator** [franz-see/Robotframework-Database-Library#56]
Lines starting with '--' are also comments in mysql. Consider adding check for those too...

```
try:
    cur = self._dbconnection.cursor()        
    sqlStatement = ''
    for line in sqlScriptFile:
        line = line.strip()
        if line.startswith('#'):
            continue
        if line.startswith('--'):
            continue
        ...
```

**Comment by jerry57** [comment]
Could you install from master/source and let me know if this is working already?  Changes are already included there, but not in the pip version currently released.

**Comment by jerry57** [comment]
Assuming your issue was resolved by installing from master.  Will get PyPi updated soon.
