### ISSUE TITLE
update databaselibrary on pypi

### ISSUE THREAD

**Issue by qitaos** [franz-see/Robotframework-Database-Library#58]
https://pypi.python.org/pypi/robotframework-databaselibrary
this site package is old version 0.6. 
People who using "pip install robotframework-databaselibrary" to install this library will install the old one. The new version in github is 0.7. 
You can add me to Maintainer on pypi. my user is qitaos. Thanks.

**Comment by jerry57** [comment]
Duplicate of issue #48 https://github.com/franz-see/Robotframework-Database-Library/issues/48
