### ISSUE TITLE
how to resolve "TypeError: expecting None or a string" when use "execute sql string" to update 

### ISSUE THREAD

**Issue by yao450860487** [franz-see/Robotframework-Database-Library#61]
when use kw "execute sql string " to do update operation, meet this issue :     TypeError: expecting None or a string.  

I do not know the reason why happen

**Comment by jerry57** [comment]
Please submit an example testcase with sql where this is happening?  Also feel free to submit a pull request and I will review and merge as soon as possible.

**Comment by jerry57** [comment]
I believe this was an issue with the sql string being submitted and has been resolved with the latest code.  If issue still present, please submit a new issue with an example testcase.
