### ISSUE TITLE
connection_manager.py logger.debug has two dbPort

### ISSUE THREAD

**Issue by qitaos** [franz-see/Robotframework-Database-Library#62]
this line has two dbPort. When use the pyodbc module will be failed.
`logger.debug ('Connecting using : %s.connect(DRIVER={SQL Server};SERVER=%s,%s;DATABASE=%s;UID=%s;PWD=%s)' % (dbapiModuleName,dbHost,dbPort,dbName,dbPort,dbUsername, dbPassword))`

**Comment by jerry57** [comment]
Version 0.8.1 now released and should resolve this issue, sorry.
