### ISSUE TITLE
Sqlite : Can't create  transaction  table name

### ISSUE THREAD

**Issue by LamhotJM** [franz-see/Robotframework-Database-Library#65]
${output} =     Execute SQL String    CREATE TABLE transaction (trx_id varchar,address_ship varchar,date_order varchar,seller_name varchar,delivery_service varchar);
    Log    ${output}
  Should Be Equal As Strings   ${output}    None

error message: OperationalError: near "transaction": syntax error

**Comment by jerry57** [comment]
"transaction" is a reserved word, so sqlite will not allow you to create a table with that name.  This is in SQLite3 not the databaselibrary.  Closing this issue
