### ISSUE TITLE
Fetch data from column of CLOB datatype.

### ISSUE THREAD

**Issue by hbijli** [franz-see/Robotframework-Database-Library#75]
Thank you so much for this library. Can you create a keyword to query a column of datatype CLOB or such variant?

**Comment by jerry57** [comment]
I am not familiar with CLOB, can you provide a SQL query type of example at least?  Would you consider taking on the creation of the keyword, I could do a review of the code and merge ultimately.

**Comment by hbijli** [comment]
Hi Jerry,


This is an Oracle datatype that stores large blocks of unstructured data (such as text, graphic images, video clips, and sound waveforms)

https://docs.oracle.com/cd/B28359_01/server.111/b28318/datatype.htm#CNCPT513


I was using cx_oracle to access the Oracle database.


I created a new keyword by updating the Query keyword and it appears to work:

    def query_column_of_lob_datatype(self, selectStatement):
        """
        Uses the input `selectStatement` to query for the values that
        will be returned as a list of tuples.

        Tip: Unless you want to log all column values of the specified rows,
        try specifying the column names in your select statements
        as much as possible to prevent any unnecessary surprises with schema
        changes and to easily see what your [] indexing is trying to retrieve
        (i.e. instead of `"select * from my_table"`, try
        `"select id, col_1, col_2 from my_table"`).

        For example, given we have a table `person` with the following data:
        | id | first_name  | last_name |
        |  1 | Franz Allan | See       |

        When you do the following:
        | @{queryResults} | Query | select * from person |
        | Log Many | @{queryResults} |

        You will get the following:
        [1, 'Franz Allan', 'See']

        Also, you can do something like this:
        | ${queryResults} | Query | select first_name, last_name from person |
        | Log | ${queryResults[0][1]}, ${queryResults[0][0]} |

        And get the following
        See, Franz Allan
        """
        cur = None
        try:
            cur = self._dbconnection.cursor()
            self.__execute_sql(cur, selectStatement)
            for row in cur:
                return row[0].read()
            #allRows = cur.fetchall()
            #return allRows
        finally :
            if cur :
                self._dbconnection.rollback()



Per comment online:

https://mail.python.org/pipermail/python-list/2009-March/527219.html


cx_Oracle implements DBAPI 2.0, then you should follow the general
guidelines in the specification:
http://www.python.org/dev/peps/pep-0249/

LOBs are an extension to DBAPI -- see
http://cx-oracle.sourceforge.net/html/lob.html and carefully read the
second note:

"""Note: Internally, Oracle uses LOB locators which are allocated based on
the cursor array size. Thus, it is important that the data in the LOB
object be manipulated before another internal fetch takes place. The
safest way to do this is to use the cursor as an iterator. In particular,
do not use the fetchall() method. The exception “LOB variable no longer
valid after subsequent fetch” will be raised if an attempt to access a LOB
variable after a subsequent fetch is detected."""


Thanks,


Haris Bijli

________________________________

**Comment by jerry57** [comment]
This all looks and sounds great.  Can you please fork the project and do a pull request with this change.  Also please include a testcase.  If you could create an Oracle testsuite that would be even better yet.
