### ISSUE TITLE
Not able to work with JayDeBeApi 1.1.1

### ISSUE THREAD

**Issue by ccthia** [franz-see/Robotframework-Database-Library#76]
Error occurs when I try to run the previous working code in using the latest JayDeBeApi 1.1.1. It causes python to crash. It works when I downgraded JayDeBeApi back to 0.2.0.

Based on the change log for JayDeBeApi, there is a change in v1.0.0 which make major changes to the connect method.
https://pypi.python.org/pypi/JayDeBeApi/#changelog

**Comment by jerry57** [comment]
Could you please send in an example of what is failing vs used to work?  In reading the documentation for JayDeBeApi it should be db-api compliant and thus accept the default connection string.  Alternately, can you submit a pull request with the changes you think are required to get this working again?

**Comment by ccthia** [comment]
Hi Jerry,

I only managed to have what used to work. This is what I used to connect
when using jaydebeapi 0.2.0. It is not working after updating to 1.1.1.
Working again after roll back jaydebeapi to 0.2.0

${JDBC_ORACLE_DRIVER}    'oracle.jdbc.driver.OracleDriver'
${JDBC_ORACLE_QA_URL}    'jdbc:oracle:thin:user/password@dbserver
:port:dbname'

Connect To Database Using Custom Params   jaydebeapi
 ${JDBC_ORACLE_DRIVER},${JDBC_ORACLE_QA_URL}

I am guessing that the connect method is changed based on their change log:
1.0.0 - 2017-01-10

   - *Allow for db properties to be passed to the connect method. Probably
   incompatible to code based on previous versions.* See documentation of
   the connect method. (Thanks @testlnord for you efforts and the patience.)
   - New major version due to possible api incompatibility.


I found that some other user got the similar problem
http://stackoverflow.com/questions/41646041/jaydebeapi-latest-update-to-1-0-0-causing-connection-error

Rgds,
Chang Chao

**Comment by GerwinLaagland** [comment]
I was struggling with this combination as well, but got this solution to work. 

This example contains DB2, but I think the way to work with this should be clear:

```
*** Variables ***
@{JDBC DRIVERS}        ${EXECDIR}${/}Resources${/}DB2${/}db2jcc.jar    
                ...    ${EXECDIR}${/}Resources${/}DB2${/}db2jcc_license_cisuz.jar
                ...    ${EXECDIR}${/}Resources${/}DB2${/}db2jcc_license_cu.jar

*** Keywords ***
Create DB2 connection
     @{Credentials}=    create list    username   password

     Connect To Database Using Custom Params   jaydebeapi    'com.ibm.db2.jcc.DB2Driver','jdbc:db2://adress.host.com:50000/DATA_BASE:retrieveMessagesFromServerOnGetMessage=true;',${Credentials},@{JDBC DRIVERS}`
```

You'll need to create a list for your credentials, and include this as an variable. Do note that you include it as variable with dollar sign. Which is different from the array mention in the @{JDBC DRIVERS}.

So it'll turn into something like this in the earlier example:

```
Connect To Database Using Custom Params   jaydebeapi
 '${JDBC_ORACLE_DRIVER}','${JDBC_ORACLE_QA_URL}','${Credentials}'
```

Hope this resolves it! But as far as I can see not a bug in the library. Just a script compatibility issue with the JayDeBeApi.
