### ISSUE TITLE
when I run execute sql string got a ORA-00911: invalid character

### ISSUE THREAD

**Issue by aray0322** [franz-see/Robotframework-Database-Library#82]
It only happens when I exuecte multiple scripts delimited by a semi-colon.  If i only execute one script it is working fine.
robotframework  version 3.0.3
databaselibrary version  1.0.1
My code:
*** Settings ***
Library           DatabaseLibrary

*** Test Cases ***
ExecTest
    Connect To Database Using Custom Params    cx_Oracle    'username','password','myserver'
    ${sql}=    SetVariable    update imis.cust_info set qualify_status='0' where cust_no='130000002041'; update imis.cust_info set qualify_status='0' where cust_no='130000002041'
    Execute Sql String    ${sql}

Error Log:

Starting test: RobotFrameworkPros.DBTest.DB.ExecTest
20171227 14:14:49.763 :  INFO : Executing : Connect To Database Using Custom Params : cx_Oracle.connect(db_api_2.connect('username','password','myserver')) 
20171227 14:14:50.174 :  INFO : ${sql} = update imis.cust_info set qualify_status='0' where cust_no='130000002041'; update imis.cust_info set qualify_status='0' where cust_no='130000002041'
20171227 14:14:50.175 :  INFO : Executing : Execute SQL String  |  update imis.cust_info set qualify_status='0' where cust_no='130000002041'; update imis.cust_info set qualify_status='0' where cust_no='130000002041' 
20171227 14:14:50.181 :  FAIL : DatabaseError: ORA-00911: invalid character
Ending test:   RobotFrameworkPros.DBTest.DB.ExecTest

**Comment by jerry57** [comment]
I do not have an Oracle DB to run/test against right now.  If you remove the ";" (semi colon) from your SQL statement, does it then run and work?  I saw a reference similar to this at:
https://stackoverflow.com/questions/25018189/databaseerror-ora-00911-invalid-character

**Comment by jlhxxxx** [comment]
I have the same question, if I execute one sql and without the ";", it's ok. but how to execute more than one sql use a "Execute Sql String"

**Comment by jlhxxxx** [comment]
I solved this problem by putting the sql between"begin ... end;": 
```
Execute Sql String    begin sql1; sql2; end;
```

**Comment by jerry57** [comment]
As soon as I get a break in current workload, I will try to take a look at this again.
