### ISSUE TITLE
connect access files and excel

### ISSUE THREAD

**Issue by Mohamed-Heiba** [franz-see/Robotframework-Database-Library#83]
when I try to  connect a data base that I have locally as .accdb file , it fails , when I look at code found that this situation is not handled 

althougth the library support pyodbc which by python can connect easily to the file and execute the queries using only the path to file 

adding that support to it appreciated a lot 
(it should also handle the excel file as excel is also supported by pyodbc ;) )

**Comment by jerry57** [comment]
Would greatly help if you could do a pull request with the changes and some possible testcases.  I could review and merge then.  Thx

**Comment by jerry57** [comment]
This has been merged into master and will be released in next version.
