### ISSUE TITLE
Add possibility to return query results as a list of dictionaries

### ISSUE THREAD

**Issue by rhapsodyman** [franz-see/Robotframework-Database-Library#85]
Using indexes like this:
${queryResults} | Query | SELECT first_name, last_name FROM person
Log | ${queryResults[0][1]}, ${queryResults[0][0]}

is not suitable if you query many columns

It will be good to have a possibility to return query results as a list of dictionaries
for example: for such table
   | AccountID | FirstName | LastName | Address |
   | 1         |  Alex     | Blake    | Some address |
   | 2         |  John     | Blake    | Some other address |
   
   to return 
   
   [ {'AccountID' : 1, 'FirstName': Alex, 'LastName': Blake, 'Address': Some Address },
     {'AccountID' : 2, 'FirstName': John, 'LastName': Blake, 'Address': Some other Address }
   ]

**Comment by jerry57** [comment]
I agree that the current is less than optimal and a list of dictionaries might be useful.  Could you please submit a pull request with a possible solution and I will try to get it evaluated/reviewed/merged as quickly as possible?

**Comment by jerry57** [comment]
Code has been merged to master and will be released as part of the next release.  THANKS!
