### ISSUE TITLE
DB connect using mysql failed in maven

### ISSUE THREAD

**Issue by AcArjun** [franz-see/Robotframework-Database-Library#94]
showing this error "Keyword 'DatabaseLibrary.Connect To Database' expected 4 to 5 arguments, got 6"

i added maven dependency to get keywords. Do i need to configure "pymysql" anywhere in eclipse

this is the maven dependency i have added

<dependency>
    <groupId>com.github.hi-fi</groupId>
    <artifactId>robotframework-dblibrary</artifactId>
    <version>3.1.1</version>
</dependency>

**Comment by jerry57** [comment]
This project is for the python Robotframework-DatabaseLibrary.  You want to report your issue to:
https://github.com/Hi-Fi/robotframework-dblibrary
The java robotframework-dblibrary project
